# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &nixos age1de8w6nrwrjlrehq6mwmtc4dj2cpukn7xpd7kuthyqzrvv78gsvfqtmumn5
  # - &admin_bob age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl
creation_rules:
  #- path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *nixos
